// Yoga Coach pose library, routines, beginner journey, muscle map.
import { FRONT, SIDE, P } from './figure.js';

// Muscle groups (ids map to regions on the front/back body diagram)
export const MUSCLES = {
  neck: { name: 'Neck', view: 'both' },
  shoulders: { name: 'Shoulders', view: 'both' },
  chest: { name: 'Chest', view: 'front' },
  arms: { name: 'Arms', view: 'both' },
  core: { name: 'Core (belly)', view: 'front' },
  obliques: { name: 'Side waist', view: 'front' },
  hipflex: { name: 'Hip flexors', view: 'front' },
  quads: { name: 'Front thighs (quads)', view: 'front' },
  adductors: { name: 'Inner thighs', view: 'front' },
  upperback: { name: 'Upper back', view: 'back' },
  lats: { name: 'Side back (lats)', view: 'back' },
  lowback: { name: 'Lower back', view: 'back' },
  glutes: { name: 'Glutes (seat)', view: 'back' },
  hamstrings: { name: 'Back thighs (hamstrings)', view: 'back' },
  calves: { name: 'Calves & ankles', view: 'back' }
};

const STAND = FRONT;
const TABLE = P(SIDE, { torso: 90, head: 100, lu: 0, ll: 0, ru: 0, rl: 0, lt: 0, ls: -90, rt: 0, rs: -90, lf: -90, rf: -90 });
const PRONE = P(SIDE, { torso: 90, head: 92, lu: -30, ll: 80, ru: -25, rl: 85, lt: -90, ls: -90, rt: -90, rs: -90, lf: -95, rf: -95 });
const SUPINE = P(SIDE, { face: -1, torso: 90, head: 90, lu: -88, ll: -88, ru: -86, rl: -86, lt: -150, ls: -15, rt: -140, rs: -10, lf: -90, rf: -90 });
const SEATED_SIDE = P(SIDE, { torso: 180, head: 180, lu: 30, ll: 60, ru: 35, rl: 65, lt: 90, ls: 90, rt: 90, rs: 90, lf: 180, rf: 175 });
const CROSS = P(FRONT, { lt: -72, ls: 70, rt: 72, rs: -70, lf: 90, rf: -90, lu: -18, ll: -30, ru: 18, rl: 30 });

const std = (a, b, c, d) => [
  { f: 'start', t: 1.6, cap: a }, { f: 'pose', t: 2.8, cap: b }, { f: 'pose', t: 3.4, cap: c, move: false }, { f: 'start', t: 2.4, cap: d }];

export const POSES = [
  { id: 'mountain', name: 'Mountain', kid: 'Tall Giraffe', emoji: '🦒', side: false, level: 1, cam: true, anchor: 'feet',
    frames: { start: P(STAND, { head: 178, lu: -14, ru: 14 }), pose: P(STAND, { lu: -9, ll: -8, ru: 9, rl: 8, lt: -3, ls: -1, rt: 3, rs: 1 }) },
    anim: std('Stand with feet hip-width apart.', 'Press your feet down and grow tall.', 'Shoulders soft, breathe slowly.', 'Relax and shake it out.'),
    steps: ['Stand with your feet hip-width apart, toes pointing forward.', 'Press evenly through both feet and gently straighten your legs.', 'Lengthen your spine, roll your shoulders back and down.', 'Arms rest by your sides, palms facing forward. Breathe slowly.'],
    mistakes: ['Locking the knees hard', 'Leaning back or sticking the belly out', 'Shrugging shoulders up to the ears'],
    mods: ['Stand with your back near a wall for feedback', 'Feet wider apart for more balance'],
    stretch: ['chest'], strong: ['quads', 'core', 'calves'],
    muscleText: { stretch: 'Gently opens the chest', strong: 'Thighs, belly and ankles work softly to hold you tall' },
    benefit: 'Builds posture and body awareness: the base of every standing pose.',
    story: "Let's be tall giraffes reaching for the juiciest leaves at the top of the tree!" },
  { id: 'tree', name: 'Tree', kid: 'Flamingo', emoji: '🦩', side: true, level: 2, cam: true, anchor: 'feet',
    frames: { start: P(STAND, {}), pose: P(STAND, { rt: 58, rs: -62, rf: -60, lt: -1, ls: 1, lu: 158, ll: 172, ru: -158, rl: -172 }) },
    anim: std('Stand tall like a mountain.', 'Lift one foot to your ankle, calf or thigh.', 'Hands up like branches. Find a still spot to look at.', 'Lower the foot slowly.'),
    steps: ['Stand tall and shift your weight into your left foot.', 'Place your right foot on your ankle, calf, or inner thigh, never on the knee.', 'Press foot and leg into each other. Bring hands to chest or overhead.', 'Fix your eyes on one still spot and breathe. Then switch sides.'],
    mistakes: ['Pressing the foot into the side of the knee', 'Hip of the standing leg popping out to the side', 'Holding the breath'],
    mods: ['Keep your toes on the floor like a kickstand', 'Hold a wall or chair for balance'],
    stretch: ['adductors', 'hipflex'], strong: ['calves', 'quads', 'glutes', 'core'],
    muscleText: { stretch: 'Inner thigh and hip of the lifted leg', strong: 'Standing-leg ankle, thigh and seat, plus your core for balance' },
    benefit: 'Trains balance and focus.',
    story: "Let's be flamingos standing on one leg in a windy lagoon. Can you stay still while the wind blows?" },
  { id: 'warrior2', name: 'Warrior II', kid: 'Brave Lion', emoji: '🦁', side: true, level: 3, cam: true, anchor: 'bbox',
    frames: { start: P(STAND, { lt: -24, ls: -24, rt: 24, rs: 24, lf: -100, rf: 80 }), pose: P(STAND, { face: -0.9, lt: -62, ls: -4, rt: 52, rs: 52, lf: -95, rf: 75, lu: -90, ll: -90, ru: 90, rl: 90 }) },
    anim: std('Step your feet wide apart.', 'Turn the front foot out and bend that knee.', 'Arms long and level. Look past your front hand.', 'Straighten the leg and step together.'),
    steps: ['Step your feet wide, about one leg-length apart.', 'Turn your front toes out to the side, back foot slightly in.', 'Bend your front knee over your ankle, aiming for a 90° bend.', 'Reach arms out at shoulder height and gaze over the front fingers. Then switch sides.'],
    mistakes: ['Front knee falling inward (keep it over the middle toes)', 'Leaning the body toward the front leg', 'Arms drooping below shoulder height'],
    mods: ['Bend the front knee less', 'Shorten your stance', 'Rest hands on hips'],
    stretch: ['adductors', 'hipflex', 'chest'], strong: ['quads', 'glutes', 'shoulders', 'core'],
    muscleText: { stretch: 'Inner thighs, front of the back hip, chest', strong: 'Front thigh, seat, shoulders and core' },
    benefit: 'Builds leg strength and stamina.',
    story: "Let's be brave lions guarding our pride! Strong legs, long paws, and a big brave face." },
  { id: 'chair', name: 'Chair', kid: 'Invisible-Chair Bear', emoji: '🐻', side: false, level: 3, cam: true, anchor: 'feet',
    frames: { start: P(SIDE, {}), pose: P(SIDE, { torso: 158, head: 165, lt: 62, ls: -18, rt: 66, rs: -16, lu: 160, ll: 165, ru: 164, rl: 168, lf: 92, rf: 92 }) },
    anim: std('Stand with feet together or hip-width.', 'Bend your knees and sit back.', 'Arms up, weight in your heels.', 'Press up to standing.'),
    steps: ['Stand with feet hip-width apart.', 'Bend your knees and sit your hips back like sitting on a chair.', 'Reach your arms up alongside your ears.', 'Keep weight in your heels and chest lifted. Breathe.'],
    mistakes: ['Knees shooting far past the toes', 'Rounding the lower back', 'Lifting the heels'],
    mods: ['Bend the knees less', 'Hands on thighs or at the chest', 'Back against a wall'],
    stretch: ['calves', 'shoulders'], strong: ['quads', 'glutes', 'core', 'upperback'],
    muscleText: { stretch: 'Ankles and shoulders', strong: 'Front thighs, seat, core and upper back' },
    benefit: 'Builds strong legs quickly. Great for climbing stairs and lifting.',
    story: "Let's be bears sitting on an invisible chair. Shh, don't let it disappear!" },
  { id: 'downdog', name: 'Downward Dog', kid: 'Stretchy Puppy', emoji: '🐶', side: false, level: 3, cam: true, anchor: 'bbox',
    frames: { start: TABLE, pose: P(SIDE, { torso: 42, head: 32, lu: 40, ll: 40, ru: 42, rl: 42, lt: -40, ls: -38, rt: -38, rs: -36, lf: 100, rf: 100 }) },
    anim: std('Start on hands and knees.', 'Tuck your toes and lift your hips high.', 'Push the floor away. Knees can bend.', 'Lower knees back to the floor.'),
    steps: ['Start on hands and knees, hands under shoulders.', 'Tuck your toes and lift your hips up and back.', 'Press your hands into the floor and lengthen your spine.', 'Keep knees soft if hamstrings feel tight; heels reach toward the floor.'],
    mistakes: ['Rounding the back to force straight legs', 'Shoulders scrunched to the ears', 'Hands too close to the feet'],
    mods: ['Bend your knees generously', 'Hands on a chair seat or wall (Half Dog)'],
    stretch: ['hamstrings', 'calves', 'lats', 'shoulders'], strong: ['shoulders', 'arms', 'upperback'],
    muscleText: { stretch: 'Back thighs, calves, sides of the back', strong: 'Shoulders, arms and upper back' },
    benefit: 'A whole-body stretch that wakes you up.',
    story: "Let's be stretchy puppies after a nap! Wag your tail (gently wiggle your hips)." },
  { id: 'catcow', name: 'Cat-Cow', kid: 'Mooing Cow & Scaredy Cat', emoji: '🐄', side: false, level: 1, cam: false, anchor: 'bbox',
    frames: { start: TABLE, cow: P(TABLE, { arch: 9, head: 145, torso: 92 }), cat: P(TABLE, { arch: -10, head: 30, torso: 88 }) },
    anim: [{ f: 'start', t: 1.6, cap: 'Hands under shoulders, knees under hips.' }, { f: 'cow', t: 2.6, cap: 'Breathe in: belly down, look up (Cow).' }, { f: 'cat', t: 2.6, cap: 'Breathe out: round your back, chin in (Cat).' }, { f: 'cow', t: 2.6, cap: 'Breathe in: Cow.' }, { f: 'cat', t: 2.6, cap: 'Breathe out: Cat.' }, { f: 'start', t: 2, cap: 'Back to a flat table.' }],
    steps: ['Come to hands and knees, wrists under shoulders, knees under hips.', 'Inhale: let your belly sink, lift chest and gaze (Cow).', 'Exhale: round your spine to the ceiling, tuck your chin (Cat).', 'Move slowly with your breath, 5–10 rounds.'],
    mistakes: ['Moving too fast without the breath', 'Cranking the neck back in Cow'],
    mods: ['Do it seated in a chair with hands on knees', 'Pad the knees with a folded blanket'],
    stretch: ['lowback', 'upperback', 'chest', 'core', 'neck'], strong: ['core'],
    muscleText: { stretch: 'Whole spine, chest and belly take turns stretching', strong: 'Core muscles gently guide the movement' },
    benefit: 'Loosens a stiff back, great after sitting.',
    story: "Let's say MOO as we look up like a cow, and then hiss like a scaredy cat with a round back!" },
  { id: 'cobra', name: 'Cobra', kid: 'Hissing Snake', emoji: '🐍', side: false, level: 2, cam: true, anchor: 'bbox',
    frames: { start: PRONE, pose: P(PRONE, { torso: 122, head: 150, lu: -8, ll: 8, ru: -6, rl: 10, arch: 3 }) },
    anim: std('Lie on your belly, hands under shoulders.', 'Press down and lift your chest.', 'Elbows soft, shoulders down. Hiss!', 'Lower down slowly.'),
    steps: ['Lie on your belly, legs long, tops of the feet down.', 'Place hands under your shoulders, elbows hugging in.', 'Inhale and lift your chest using your back, hands just helping.', 'Keep elbows bent and shoulders away from ears. Lower on an exhale.'],
    mistakes: ['Pushing up too high and pinching the lower back', 'Shoulders hunched to ears', 'Straightening arms fully'],
    mods: ['Sphinx: rest on your forearms', 'Lift only a few inches (Baby Cobra)'],
    stretch: ['chest', 'core', 'hipflex', 'shoulders'], strong: ['lowback', 'upperback', 'glutes'],
    muscleText: { stretch: 'Chest, belly and front of the hips', strong: 'Back muscles along the spine' },
    benefit: 'Counteracts slouching and screen posture.',
    story: "Let's be snakes sliding through the grass, then lift up and hisssss!" },
  { id: 'child', name: "Child's Pose", kid: 'Sleepy Mouse', emoji: '🐭', side: false, level: 1, cam: true, anchor: 'bbox',
    frames: { start: TABLE, pose: P(SIDE, { torso: 75, head: 70, arch: -4, lu: 84, ll: 90, ru: 86, rl: 90, lt: 65, ls: -90, rt: 66, rs: -90, lf: -90, rf: -90 }) },
    anim: std('Start on hands and knees.', 'Sit your hips back toward your heels.', 'Forehead down, arms long. Rest and breathe.', 'Walk your hands back and come up.'),
    steps: ['Kneel with big toes touching and knees as wide as comfortable.', 'Sit your hips back toward your heels.', 'Fold forward and rest your forehead on the floor or a pillow.', 'Arms long in front or resting by your sides. Breathe into your back.'],
    mistakes: ['Forcing hips down when knees hurt', 'Holding tension in the shoulders'],
    mods: ['Put a pillow between hips and heels', 'Rest forehead on stacked fists', 'Widen your knees'],
    stretch: ['lowback', 'glutes', 'lats', 'quads', 'calves'], strong: [],
    muscleText: { stretch: 'Lower back, hips, front of thighs and ankles', strong: 'Nothing! This is a resting pose' },
    benefit: 'Calms the body; a rest break any time.',
    story: "Let's be sleepy mice curled up in a cozy little ball. Squeak... zzz." },
  { id: 'butterfly', name: 'Butterfly', kid: 'Fluttering Butterfly', emoji: '🦋', side: false, level: 1, cam: true, anchor: 'bbox',
    frames: { start: P(FRONT, { lt: -55, ls: 55, rt: 55, rs: -55, lu: -10, ll: 5, ru: 10, rl: -5, lf: 90, rf: -90 }), pose: P(FRONT, { lt: -78, ls: 62, rt: 78, rs: -62, lu: 12, ll: 40, ru: -12, rl: -40, lf: 90, rf: -90 }), flap: P(FRONT, { lt: -62, ls: 64, rt: 62, rs: -64, lu: 12, ll: 40, ru: -12, rl: -40, lf: 90, rf: -90 }) },
    anim: [{ f: 'start', t: 1.6, cap: 'Sit tall and bend your knees.' }, { f: 'pose', t: 2.4, cap: 'Soles of the feet together, knees out wide.' }, { f: 'flap', t: 1, cap: 'Gently flutter your knees like wings.', mt: 0.9 }, { f: 'pose', t: 1, cap: 'Flutter, flutter.', mt: 0.9 }, { f: 'flap', t: 1, cap: 'Flutter, flutter.', mt: 0.9 }, { f: 'pose', t: 2.4, cap: 'Now sit still and breathe tall.' }, { f: 'start', t: 2, cap: 'Bring your knees together.' }],
    steps: ['Sit tall and bring the soles of your feet together.', 'Let your knees fall out to the sides.', 'Hold your ankles or feet and lengthen your spine.', 'Optionally flutter your knees, then hold still and breathe.'],
    mistakes: ['Pushing the knees down with hands', 'Slouching the lower back'],
    mods: ['Sit on a folded blanket', 'Move the feet farther from the hips'],
    stretch: ['adductors', 'glutes'], strong: ['lowback', 'core'],
    muscleText: { stretch: 'Inner thighs and hips', strong: 'Back and core muscles that hold you upright' },
    benefit: 'Opens tight hips from sitting all day.',
    story: "Let's be butterflies flapping our wings over a field of flowers. Flap, flap!" },
  { id: 'bridge', name: 'Bridge', kid: "Beaver's Bridge", emoji: '🦫', side: false, level: 2, cam: true, anchor: 'bbox',
    frames: { start: SUPINE, pose: P(SUPINE, { torso: 66, head: 90, lt: -118, ls: -8, rt: -112, rs: -4 }) },
    anim: std('Lie on your back, knees bent, feet flat.', 'Press your feet down and lift your hips.', 'Squeeze your seat, breathe.', 'Lower your spine down slowly.'),
    steps: ['Lie on your back with knees bent and feet flat, hip-width apart.', 'Arms rest by your sides, palms down.', 'Press into your feet and lift your hips toward the sky.', 'Keep knees pointing forward. Lower slowly, one bone at a time.'],
    mistakes: ['Knees falling out to the sides', 'Turning the head while up', 'Pushing the hips too high and arching the low back'],
    mods: ['Lift only a little', 'Place a pillow under your hips (supported bridge)'],
    stretch: ['hipflex', 'chest', 'quads'], strong: ['glutes', 'hamstrings', 'lowback', 'core'],
    muscleText: { stretch: 'Front of hips, chest and front thighs', strong: 'Seat, back thighs and lower back' },
    benefit: 'Wakes up glutes that get sleepy from sitting.',
    story: "Let's build a beaver bridge so the toy cars can drive under it! Vroom!" },
  { id: 'seatedfold', name: 'Seated Forward Fold', kid: 'Snuggly Turtle', emoji: '🐢', side: false, level: 1, cam: true, anchor: 'bbox',
    frames: { start: SEATED_SIDE, pose: P(SEATED_SIDE, { torso: 118, head: 112, arch: -4, lu: 96, ll: 92, ru: 98, rl: 94, lt: 90, ls: 92, rt: 90, rs: 92 }) },
    anim: std('Sit tall with legs long in front.', 'Hinge forward from your hips.', 'Hands rest on shins. Breathe and soften.', 'Roll up slowly.'),
    steps: ['Sit with legs straight in front of you. Bend knees if you need to.', 'Inhale and sit tall.', 'Exhale and hinge forward from your hips, hands sliding toward your feet.', 'Rest where you feel a gentle stretch; never force.'],
    mistakes: ['Rounding the upper back to reach the toes', 'Locking the knees'],
    mods: ['Bend your knees a lot', 'Sit on a folded blanket', 'Use a towel around your feet'],
    stretch: ['hamstrings', 'lowback', 'calves'], strong: [],
    muscleText: { stretch: 'Back of thighs, lower back and calves', strong: 'Mostly a stretch: relax into it' },
    benefit: 'Eases tight hamstrings and calms the mind.',
    story: "Let's be turtles tucking into our cozy shells." },
  { id: 'neck', name: 'Neck Stretch', kid: 'Curious Owl', emoji: '🦉', side: false, level: 1, cam: false, anchor: 'feet',
    frames: { start: CROSS, right: P(CROSS, { head: 152 }), left: P(CROSS, { head: 208 }) },
    anim: [{ f: 'start', t: 1.6, cap: 'Sit or stand tall, shoulders relaxed.' }, { f: 'right', t: 3.4, cap: 'Tip your ear toward your right shoulder.' }, { f: 'start', t: 2, cap: 'Back to center.' }, { f: 'left', t: 3.4, cap: 'Now ear toward your left shoulder.' }, { f: 'start', t: 2, cap: 'Center. Gently nod yes.' }],
    steps: ['Sit or stand tall and let your shoulders drop.', 'Tip your right ear toward your right shoulder.', 'Breathe for a few breaths, keeping the opposite shoulder down.', 'Return to center and switch sides.'],
    mistakes: ['Lifting the shoulder up to the ear', 'Rolling the head all the way back'],
    mods: ['Use a hand to gently add weight', 'Make the movement smaller'],
    stretch: ['neck', 'shoulders'], strong: [],
    muscleText: { stretch: 'Sides of the neck and tops of the shoulders', strong: 'Not a strength move: let it be easy' },
    benefit: 'Releases tension from screens and phones.',
    story: "Let's be curious owls looking at the stars. Hoo-hoo!" },
  { id: 'shoulder', name: 'Shoulder Stretch', kid: 'Hugging Koala', emoji: '🐨', side: true, level: 1, cam: false, anchor: 'feet',
    frames: { start: STAND, pose: P(STAND, { ru: -95, rl: -92, lu: 40, ll: 115 }) },
    anim: std('Stand tall.', 'Bring one arm across your chest.', 'Hug it in with the other arm. Shoulders down.', 'Release and switch.'),
    steps: ['Stand or sit tall.', 'Bring your right arm straight across your chest.', 'Hold it with your left hand above or below the elbow.', 'Keep the shoulder down, breathe, then switch sides.'],
    mistakes: ['Pulling on the elbow joint', 'Shrugging the shoulder'],
    mods: ['Keep the elbow bent', 'Do it seated at your desk'],
    stretch: ['shoulders', 'upperback'], strong: [],
    muscleText: { stretch: 'Back of the shoulder and upper back', strong: 'Not a strength move' },
    benefit: 'Relieves desk-tight shoulders.',
    story: "Let's be koalas giving a big hug to a eucalyptus tree!" },
  { id: 'forwardfold', name: 'Standing Forward Fold', kid: 'Swinging Elephant', emoji: '🐘', side: false, level: 2, cam: true, anchor: 'feet',
    frames: { start: SIDE, pose: P(SIDE, { torso: 22, head: 10, lu: 2, ll: 0, ru: 4, rl: 2, lt: 6, ls: -6, rt: 8, rs: -6 }) },
    anim: std('Stand tall, feet hip-width.', 'Bend your knees and fold forward from the hips.', 'Let your head and arms hang heavy.', 'Roll up slowly, head comes last.'),
    steps: ['Stand with feet hip-width apart.', 'Soften your knees and fold forward from your hips.', 'Let your head hang and hold opposite elbows or let your arms dangle.', 'To come up, bend the knees and roll up slowly.'],
    mistakes: ['Locking the knees', 'Coming up too fast (can feel dizzy)'],
    mods: ['Bend your knees a lot', 'Rest hands on a chair or your thighs'],
    stretch: ['hamstrings', 'calves', 'lowback', 'neck'], strong: ['quads'],
    muscleText: { stretch: 'Back thighs, calves and lower back', strong: 'Front thighs lightly' },
    benefit: 'Releases the back and calms a busy mind.',
    story: "Let's be elephants swinging our long trunks side to side!" },
  { id: 'star', name: 'Star Pose', kid: 'Starfish', emoji: '⭐', side: false, level: 1, cam: true, anchor: 'bbox',
    frames: { start: STAND, pose: P(STAND, { lu: -130, ll: -130, ru: 130, rl: 130, lt: -26, ls: -26, rt: 26, rs: 26, lf: -110, rf: 110 }) },
    anim: std('Stand tall.', 'Step wide and reach your arms up and out.', 'Shine bright! Reach out through fingers and toes.', 'Step back together.'),
    steps: ['Step your feet wide apart.', 'Reach your arms up and out into a big X.', 'Spread your fingers and reach in all five directions.', 'Breathe and shine.'],
    mistakes: ['Shoulders lifting to ears', 'Knees locked back'],
    mods: ['Arms at shoulder height', 'Smaller stance'],
    stretch: ['chest', 'adductors'], strong: ['shoulders', 'quads', 'core'],
    muscleText: { stretch: 'Chest and inner thighs', strong: 'Shoulders, thighs and core' },
    benefit: 'Energizing and confidence-boosting.',
    story: "Let's be starfish shining at the bottom of the sea!" },
  { id: 'sidebend', name: 'Standing Side Bend', kid: 'Swaying Palm Monkey', emoji: '🐒', side: true, level: 1, cam: true, anchor: 'feet',
    frames: { start: STAND, pose: P(STAND, { torso: 160, head: 158, lu: 150, ll: 140, ru: 168, rl: 150 }) },
    anim: std('Stand tall, feet hip-width.', 'Reach your arms up, then lean gently to one side.', 'Feel the long stretch along your side.', 'Back to center.'),
    steps: ['Stand tall and reach both arms overhead.', 'Hold one wrist and lean gently to the side.', 'Keep both feet grounded and hips steady.', 'Breathe into your side ribs, then switch.'],
    mistakes: ['Leaning forward instead of sideways', 'Collapsing into the lower side'],
    mods: ['One hand on hip', 'Do it seated'],
    stretch: ['obliques', 'lats', 'shoulders'], strong: ['core'],
    muscleText: { stretch: 'Sides of your waist and back', strong: 'Opposite-side core muscles hold you' },
    benefit: 'Creates space for breathing and loosens the sides.',
    story: "Let's be monkeys swaying from a palm tree in the breeze!" },
  { id: 'lunge', name: 'Low Lunge', kid: 'Leaping Frog', emoji: '🐸', side: true, level: 2, cam: true, anchor: 'bbox',
    frames: { start: P(SIDE, { lt: 75, ls: 0, rt: -15, rs: -88, rf: -95, lf: 90, torso: 180 }), pose: P(SIDE, { torso: 176, head: 176, lt: 78, ls: -4, rt: -40, rs: -88, rf: -95, lu: 170, ll: 175, ru: 172, rl: 176 }) },
    anim: std('Step one foot forward, back knee down.', 'Slide your hips gently forward.', 'Arms up if it feels good. Breathe.', 'Release and switch legs.'),
    steps: ['From kneeling, step your right foot forward, knee over ankle.', 'Lower your back knee onto a soft surface.', 'Slide hips gently forward until the front of the back hip stretches.', 'Hands on knee or arms up. Then switch sides.'],
    mistakes: ['Front knee far past the ankle', 'Arching the low back a lot'],
    mods: ['Pad the back knee', 'Hands on blocks or a chair'],
    stretch: ['hipflex', 'quads'], strong: ['glutes', 'quads', 'core'],
    muscleText: { stretch: 'Front of the back hip and thigh', strong: 'Front-leg seat and thigh, and core' },
    benefit: 'The best antidote to long hours of sitting.',
    story: "Let's be frogs getting ready for a giant leap across the pond!" },
  { id: 'easyseat', name: 'Easy Seat Breathing', kid: 'Calm Koala Breath', emoji: '🐼', side: false, level: 1, cam: false, anchor: 'bbox',
    frames: { start: CROSS, in: P(CROSS, { arch: 0, head: 180, lu: -16, ru: 16 }), out: P(CROSS, { arch: 0, head: 185, lu: -22, ru: 22 }) },
    anim: [{ f: 'start', t: 1.6, cap: 'Sit cross-legged, hands on knees.' }, { f: 'in', t: 4, cap: 'Breathe in for four...', mt: 3.5 }, { f: 'out', t: 4, cap: 'Breathe out for four...', mt: 3.5 }, { f: 'in', t: 4, cap: 'Breathe in, belly grows like a balloon.', mt: 3.5 }, { f: 'out', t: 4, cap: 'Breathe out, slow and soft.', mt: 3.5 }],
    steps: ['Sit cross-legged or on a chair, spine tall.', 'Rest your hands on your knees.', 'Breathe in through your nose for 4 counts.', 'Breathe out for 4–6 counts. Repeat.'],
    mistakes: ['Slumping', 'Forcing big breaths'],
    mods: ['Sit on a cushion or chair', 'Lean back against a wall'],
    stretch: ['adductors', 'glutes'], strong: ['core', 'lowback'],
    muscleText: { stretch: 'Hips and outer thighs gently', strong: 'Postural back and belly muscles' },
    benefit: 'Calms the nervous system and helps focus.',
    story: "Let's be calm pandas smelling a flower (breathe in) and blowing out a candle (breathe out)." },
  { id: 'kneeschest', name: 'Knees to Chest', kid: 'Rolling Hedgehog', emoji: '🦔', side: false, level: 1, cam: false, anchor: 'bbox',
    frames: { start: SUPINE, pose: P(SUPINE, { lt: -205, ls: 40, rt: -200, rs: 45, lu: -150, ll: -195, ru: -145, rl: -190, lf: 180, rf: 180 }) },
    anim: std('Lie on your back, knees bent.', 'Hug your knees in toward your chest.', 'Rock gently side to side.', 'Feet back to the floor.'),
    steps: ['Lie on your back.', 'Draw both knees toward your chest.', 'Hold behind your thighs or on your shins.', 'Rock gently side to side to massage your back.'],
    mistakes: ['Lifting the head off the floor', 'Pulling hard on the knees'],
    mods: ['One knee at a time', 'Hold behind the thighs'],
    stretch: ['lowback', 'glutes'], strong: [],
    muscleText: { stretch: 'Lower back and seat', strong: 'Relaxing release' },
    benefit: 'Soothes a tired lower back.',
    story: "Let's be hedgehogs curling into a tiny ball and rolling!" }
];
export const POSE = Object.fromEntries(POSES.map(p => [p.id, p]));

// step: [poseId, holdSeconds]
const S = (id, hold) => ({ id, hold });
export const JOURNEY = [
  { week: 1, title: 'Week 1 · Meet Your Body', days: [
    { name: 'First Breaths', steps: [S('easyseat', 40), S('neck', 30), S('shoulder', 20), S('catcow', 40), S('child', 40), S('mountain', 30)] },
    { name: 'Gentle Spine', steps: [S('mountain', 30), S('sidebend', 20), S('catcow', 45), S('child', 40), S('kneeschest', 40), S('easyseat', 40)] },
    { name: 'Hip Hello', steps: [S('easyseat', 30), S('butterfly', 40), S('catcow', 40), S('child', 40), S('kneeschest', 40), S('seatedfold', 30)] },
    { name: 'Standing Tall', steps: [S('mountain', 40), S('star', 25), S('sidebend', 25), S('neck', 30), S('shoulder', 25), S('child', 40), S('easyseat', 40)] }] },
  { week: 2, title: 'Week 2 · Balance & Backbends', days: [
    { name: 'First Tree', steps: [S('mountain', 30), S('tree', 25), S('star', 25), S('catcow', 45), S('cobra', 20), S('child', 45), S('seatedfold', 40), S('easyseat', 40)] },
    { name: 'Snake Day', steps: [S('easyseat', 30), S('catcow', 45), S('cobra', 25), S('child', 40), S('cobra', 25), S('butterfly', 45), S('kneeschest', 45)] },
    { name: 'Hamstring Helper', steps: [S('mountain', 30), S('forwardfold', 30), S('sidebend', 30), S('tree', 30), S('seatedfold', 45), S('butterfly', 40), S('kneeschest', 45)] },
    { name: 'Week 2 Flow', steps: [S('easyseat', 30), S('neck', 30), S('catcow', 45), S('cobra', 25), S('child', 40), S('mountain', 30), S('tree', 30), S('forwardfold', 30), S('seatedfold', 45)] }] },
  { week: 3, title: 'Week 3 · Strength', days: [
    { name: 'Meet the Warrior', steps: [S('mountain', 30), S('star', 25), S('warrior2', 25), S('sidebend', 30), S('forwardfold', 30), S('catcow', 45), S('child', 45), S('bridge', 25), S('easyseat', 45)] },
    { name: 'First Down Dog', steps: [S('catcow', 45), S('downdog', 20), S('child', 40), S('downdog', 25), S('cobra', 25), S('child', 40), S('lunge', 30), S('seatedfold', 45), S('kneeschest', 45)] },
    { name: 'Strong Legs', steps: [S('mountain', 30), S('chair', 20), S('forwardfold', 30), S('warrior2', 30), S('tree', 30), S('chair', 25), S('bridge', 30), S('butterfly', 45), S('easyseat', 45)] },
    { name: 'Week 3 Flow', steps: [S('easyseat', 30), S('catcow', 45), S('downdog', 30), S('lunge', 30), S('mountain', 20), S('warrior2', 30), S('tree', 30), S('bridge', 30), S('seatedfold', 45), S('child', 45)] }] },
  { week: 4, title: 'Week 4 · Put It Together', days: [
    { name: 'Full Body Flow', steps: [S('easyseat', 40), S('neck', 30), S('catcow', 50), S('downdog', 35), S('lunge', 35), S('mountain', 25), S('chair', 25), S('warrior2', 35), S('tree', 35), S('cobra', 30), S('child', 45), S('bridge', 35), S('seatedfold', 50)] },
    { name: 'Balance Day', steps: [S('mountain', 30), S('tree', 40), S('star', 30), S('warrior2', 35), S('sidebend', 30), S('chair', 30), S('forwardfold', 40), S('butterfly', 50), S('kneeschest', 45), S('easyseat', 50)] },
    { name: 'Deep Stretch', steps: [S('easyseat', 40), S('catcow', 50), S('child', 50), S('cobra', 30), S('downdog', 40), S('lunge', 40), S('seatedfold', 60), S('butterfly', 60), S('bridge', 35), S('kneeschest', 50)] },
    { name: 'Graduation Flow', steps: [S('easyseat', 40), S('mountain', 30), S('star', 30), S('chair', 30), S('warrior2', 40), S('tree', 40), S('forwardfold', 35), S('downdog', 40), S('cobra', 30), S('child', 45), S('bridge', 40), S('seatedfold', 50), S('easyseat', 45)] }] }
];

export const ROUTINES = [
  { id: 'morning', name: 'Morning Wake-Up', emoji: '🌅', desc: '6 min · gentle energy', steps: [S('easyseat', 30), S('catcow', 40), S('downdog', 25), S('mountain', 20), S('star', 20), S('sidebend', 25), S('forwardfold', 30), S('tree', 25)] },
  { id: 'desk', name: 'Desk Stretch', emoji: '💻', desc: '4 min · neck, shoulders, hips', steps: [S('neck', 40), S('shoulder', 25), S('sidebend', 25), S('mountain', 20), S('forwardfold', 30), S('lunge', 25)] },
  { id: 'bedtime', name: 'Bedtime Calm', emoji: '🌙', desc: '7 min · slow and sleepy', steps: [S('easyseat', 45), S('catcow', 45), S('child', 60), S('butterfly', 50), S('seatedfold', 50), S('kneeschest', 50), S('easyseat', 50)] },
  { id: 'family', name: 'Family Fun', emoji: '🎉', desc: '6 min · animal adventure', family: true, steps: [S('mountain', 15), S('tree', 15), S('star', 15), S('butterfly', 20), S('cobra', 15), S('downdog', 15), S('catcow', 25), S('chair', 12), S('warrior2', 15), S('child', 25)] }
];

export const ADVENTURE_INTRO = "Once upon a time, two explorers set off on an animal adventure. Every animal they met taught them a new shape!";
